fields:
  categoria:
    type: relationship
    rules:
      - required
  slug:
    type: string[255]
    role: slug
    slug: nombre
    behavior: hidden
  nombre:
    type: string[255]
    rules:
      - required
  descripcion:
    type: text
    legend: >
      Descripci&oacute;n
    rules:
      - required
  caracteristicas:
    type: text
    legend: >
      Caracter&iacute;sticas
    rules:
      - required
  tip:
    type: text
    legend: >
      Tips (Sab&iacute;as que)
    class: ''
    role: default
    rules:
      - required
  status:
    type: enum
    legend: >
      Estado
    default: inactive
    role: radios
    options:
      - active
      - inactive
    labels:
      active: >
        P&uacute;blico
      inactive: >
        Borrador
    translatable: no
  highlighted:
    type: enum
    legend: >
      Destacado
    default: >
      no
    role: radios
    options:
      - >
        yes
      - >
        no
    labels:
      yes: >
        S&iacute;
      no: >
        No
    translatable: no
setup:
  type: multifile
  title: Productos
  head:
    - nombre
  translatable: yes
  image:
    rules:
      - image
      - >
        mimes:jpeg,png
      - >
        image_size:>=400,>=400
      - >
        image_size:<=600,<=600
    params:
      maxlength: 1
      accept: jpg|jpeg|png
      output: jpg
      limit: 1
      retinable: 2x
    info: >
      Resoluci&oacute;n recomendada: 800x800 p&iacute;xeles.
      Resoluci&oacute;n m&aacute;xima: 1200x1200 p&iacute;xeles.
  sizes:
    - e600x600
    - c400x400
    - c350x350
    - c270x390
    - a140x140
  legend:
    field: status
    values:
      - active
      - inactive
    colors:
      active: success
      inactive: danger
    labels:
      active: >
        P&uacute;blico
      inactive: >
        Borrador
order: 30