fields:
  categoria:
    type: relationship
    rules:
      - required
  slug:
    type: string[255]
    role: slug
    slug: nombre
    behavior: hidden
  nombre:
    type: string[255]
    rules:
      - required
  color:
    type: colorpicker
    legend: >
      Color de Fondo
    default: >
      #fff0e1
    rules:
      - required
    translatable: no
  descripcion:
    type: text
    legend: >
      Descripci&oacute;n
    rules:
      - required
  caracteristicas:
    type: text
    legend: >
      Caracter&iacute;sticas
    rules:
      - required
  tip:
    type: text
    legend: >
      Tips (Sab&iacute;as que)
    class: ''
    role: default
    rules:
      - required
  status:
    type: enum
    legend: >
      Estado
    default: inactive
    role: radios
    options:
      - active
      - inactive
    labels:
      active: >
        P&uacute;blico
      inactive: >
        Borrador
    translatable: no
  highlighted:
    type: enum
    legend: >
      Destacado
    default: >
      no
    role: radios
    options:
      - >
        yes
      - >
        no
    labels:
      yes: >
        S&iacute;
      no: >
        No
    translatable: no
setup:
  type: multifile
  title: Productos
  head:
    - nombre
  translatable: yes
  image:
    rules:
      - image
      - >
        mimes:jpeg,png
      - >
        image_size:>=270,>=350
      - >
        image_size:<=800,<=800
    params:
      maxlength: 2
      accept: jpg|jpeg|png
      output: jpg
      limit: 2
      retinable: 2x
      cropped: no
    info: |
      Resoluci&oacute;n m&iacute;nima: 540x700 p&iacute;xeles.
      Resoluci&oacute;n m&aacute;xima: 1600x1600 p&iacute;xeles.
      Las im&aacute;genes deben subirse en el siguiente orden:
      1. La imagen que aparece en la Lista: (540x780 p&iacute;xeles)
      2. La imagen de la marca del Producto: (700x700 p&iacute;xeles)
  sizes:
    - e800x800
    - p270x350
    - a140x140
  text:
    title: >
      Banner del Producto
    rules:
      - image
      - >
        mimes:jpeg,png
      - >
        image_size:>=1600,>=1600
      - >
        image_size:<=2000,<=2000
    params:
      maxlength: 1
      accept: jpg|jpeg|png
      output: jpg
      limit: 1
    info: >
      Resoluci&oacute;n m&iacute;nima: 1600x1600 p&iacute;xeles.
      Resoluci&oacute;n m&aacute;xima: 2000x2000 p&iacute;xeles.
    sizes:
      - e2000x2000
      - p1600x1600
      - a140x140
  legend:
    field: status
    values:
      - active
      - inactive
    colors:
      active: success
      inactive: danger
    labels:
      active: >
        P&uacute;blico
      inactive: >
        Borrador
order: 30