fields:
  categoria:
    type: relationship
    rules:
      - required
  slug:
    type: string[255]
    role: slug
    slug: nombre
    behavior: hidden
  nombre:
    type: string[255]
    rules:
      - required
  status:
    type: enum
    legend: >
      Estado
    default: inactive
    role: radios
    options:
      - active
      - inactive
    labels:
      active: >
        P&uacute;blico
      inactive: >
        Borrador
    translatable: no
  highlighted:
    type: enum
    legend: >
      Destacado
    default: >
      no
    role: radios
    options:
      - >
        yes
      - >
        no
    labels:
      yes: >
        S&iacute;
      no: >
        No
    translatable: no
setup:
  type: multifile
  title: Productos
  head:
    - nombre
  image:
    rules:
      - image
      - >
        mimes:png
      - >
        image_size:>=588,>=373
    params:
      maxlength: 1
      accept: png
      output: png
      limit: 1
      retinable: 2x
    info: >
      Resoluci&oacute;n recomendada: 1176x746 p&iacute;xeles.
      Solo im&aacute;genes PNG con Fondo Transparente.
  sizes:
    - e600x600
    - c588x373
    - c417x263
    - a140x140
  legend:
    field: status
    values:
      - active
      - inactive
    colors:
      active: success
      inactive: danger
    labels:
      active: >
        P&uacute;blico
      inactive: >
        Borrador
order: 30